// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YOLOv4MLNet;

namespace YOLOv4MLNet.Migrations
{
    [DbContext(typeof(PictureContext))]
    [Migration("20211208184123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("YOLOv4MLNet.PictureObject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("label")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("picture")
                        .HasColumnType("BLOB");

                    b.Property<float>("x1")
                        .HasColumnType("REAL");

                    b.Property<float>("x2")
                        .HasColumnType("REAL");

                    b.Property<float>("y1")
                        .HasColumnType("REAL");

                    b.Property<float>("y2")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("PictureEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
